version: "3.0"

services:
  rasa:
    image: rasa/rasa:latest-full
    networks:
      - rasa-network
    ports:
      - "5005:5005"
    volumes:
      - "../../rasa/:/app/"
    command:
      - run
      - --cors
      - "*"
      - --enable-api
      - --debug
      - --auth-token
      - examplesecret

  action_server:
    image: rasa/rasa-sdk:latest
    networks:
      - rasa-network
    ports:
      - "5055:5055"
    volumes:
      - "../../rasa/actions:/app/actions"

  duckling:
    image: rasa/duckling:latest
    networks:
      - rasa-network
    ports:
      - "8030:8030"

  redis:
    image: redis:6.2-alpine
    restart: always
    networks:
      - rasa-network
      - admin-network
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - "./redis-data:/data"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      HTTP_USER: root
      HTTP_PASSWORD: root
    networks:
      - admin-network
    ports:
      - "8081:8081"

networks:
  rasa-network: {}
  admin-network: {}
